Fix Public IP detection - Fix issue when seeip.org is unreachable #1241
angristan/openvpn-install pull request #1243
Opened 2024-08-10 18:38 UTC by ralphg6

The script does work when seeip.org is unreachable, so I changed the policy to define the public IP.

It solves the issue #1241

## CHANGELOG

### Added

- Connection timeout on each try to solve the IP, to avoid long awaits;
- Extra public IP providers as fail overs;

### Changed

- the script just will try to solve an IP if the ENDPOINT is empty;

### Removed

- Unneeded output of CURL commands on IP detection;
- Duplicated code

2024-08-10 18:48 UTC, ralphg6 commented
Solves #1241

2024-08-19 09:18 UTC, alaz approved these changes

2024-11-07 19:42 UTC, angristan requested changes

2024-11-07 19:42 UTC, angristan commented on openvpn-install.sh
> +		PUBLIC_IP=$(curl -f -m 5 -sS --retry 2 --retry-connrefused $CURL_IP_VERSION_FLAG https://ip.seeip.org 2>/dev/null)
cf https://github.com/angristan/openvpn-install/pull/1252

```suggestion
	# If there is no public ip yet, we'll try to solve it using: https://api.seeip.org
	if [[ -z $PUBLIC_IP ]]; then
		PUBLIC_IP=$(curl -f -m 5 -sS --retry 2 --retry-connrefused $CURL_IP_VERSION_FLAG https://api.seeip.org 2>/dev/null)
```

2024-11-07 19:43 UTC, angristan commented
Thanks 🙏 I updated the seeip.org endpoint

2024-11-07 19:44 UTC, angristan commented on openvpn-install.sh
> +		>&2 echo "Couldn't solve the public IP"
```suggestion
		echo >&2 echo "Couldn't solve the public IP"
```

2024-11-07 19:55 UTC, merged

2024-11-07 19:55 UTC, angristan commented
Thanks again, this is great 😄