OpenVPN 2.4 update
angristan/openvpn-install pull request #33
Opened 2017-02-06 11:06 UTC by Angristan

As OpenVPN 2.4 is out, some improvements will be implemented to the script.

- [ ]
- [ ]

2017-02-06 16:20 UTC, m0r0n commented
"Use an ECDSA certificate"

Which ciphers will you consider safe? We have those:

`openvpn --show-curves
Available Elliptic curves, listed in order of preference:

secp521r1
brainpoolP512r1
secp384r1
brainpoolP384r1
secp256r1
secp256k1
brainpoolP256r1
secp224r1
secp224k1
secp192r1
secp192k1
`

First I was about to use secp521r1, because it sounded secure and everything, but then I read horrible things on the internet and decided to not use it. In the end I decided for secp256k1 as my personal favorite for now as E-521 or Curve25519 or others are not available.

2017-02-06 18:27 UTC, Angristan commented
What horribles things did you read ? secp521r1, brainpoolP512r1, secp384r1 and brainpoolP384r1 seems fine.

2017-02-07 09:34 UTC, m0r0n commented
It's in german, but leading to a lot of interesting details about the random curves: https://www.heise.de/forum/heise-Security/News-Kommentare/Webseiten-Verschluesselung-Viel-Nachbesserung-notwendig/Schneier-Bernstein-Elliptische-Kurven-des-NIST-nicht-vertrauenswuerdig/posting-4876878/show/

I am not a crypto expert though! I decided to use secp256k1 in the end.

2017-02-16 17:27 UTC, Angristan commented
Interesting indeed, there is also this : https://bitcoinmagazine.com/articles/satoshis-genius-unexpected-ways-in-which-bitcoin-dodged-some-cryptographic-bullet-1382996984/

In OpenVPN 2.4, the follwing curves are available : 
```
root@server:~# openvpn --show-curves
Available Elliptic curves:
secp112r1
secp112r2
secp128r1
secp128r2
secp160k1
secp160r1
secp160r2
secp192k1
secp224k1
secp224r1
secp256k1
secp384r1
secp521r1
prime192v1
prime192v2
prime192v3
prime239v1
prime239v2
prime239v3
prime256v1
sect113r1
sect113r2
sect131r1
sect131r2
sect163k1
sect163r1
sect163r2
sect193r1
sect193r2
sect233k1
sect233r1
sect239k1
sect283k1
sect283r1
sect409k1
sect409r1
sect571k1
sect571r1
c2pnb163v1
c2pnb163v2
c2pnb163v3
c2pnb176v1
c2tnb191v1
c2tnb191v2
c2tnb191v3
c2pnb208w1
c2tnb239v1
c2tnb239v2
c2tnb239v3
c2pnb272w1
c2pnb304w1
c2tnb359v1
c2pnb368w1
c2tnb431r1
wap-wsg-idm-ecid-wtls1
wap-wsg-idm-ecid-wtls3
wap-wsg-idm-ecid-wtls4
wap-wsg-idm-ecid-wtls5
wap-wsg-idm-ecid-wtls6
wap-wsg-idm-ecid-wtls7
wap-wsg-idm-ecid-wtls8
wap-wsg-idm-ecid-wtls9
wap-wsg-idm-ecid-wtls10
wap-wsg-idm-ecid-wtls11
wap-wsg-idm-ecid-wtls12
Oakley-EC2N-3
Oakley-EC2N-4
```

We can eliminate `secp*r*` and thus `prime*v*` (see https://crypto.stackexchange.com/questions/33052/is-there-any-difference-between-nist-and-secp-curves-in-terms-of-their-algorithm)

There not much simple documentation on ellitpic curves, but as Bitcoin uses `secp256k1`, we can assume it's a solid choice so I'll go with this one for now, until someone with more knowledge on the subject can advice us. :)

2017-02-16 19:00 UTC, Angristan commented
As for now, everything is working fine (tested with Debian 8 as the server and W10 as the client). I noticed that OpenVPN used AES-256-GCM even though I specified AES-128-GCM on both sides... I suppose that OpenVPN tries to use the strongest cipher available. I would prefer to use AES-128-GCM which is already really strong. I'll take a look later.

2017-02-16 19:31 UTC, Angristan commented
ECDSA certificate working great \o/ 

The installation is now very fast.

It seems that it breaks tls-auth but I will replace it with tls-crypt anyway.

2017-02-16 21:36 UTC, Angristan commented
N.B. `tls-auth` add an authentication layer to the TLS control channel, whereas` tls-crypt` adds an authentication **and** encryption layer to it.

2017-02-18 17:02 UTC, Kcchouette commented
@Angristan for android, why not using the official port apps? (this one: https://github.com/schwabe/ics-openvpn or https://play.google.com/store/apps/details?id=de.blinkt.openvpn)

2017-02-23 21:18 UTC, tapir commented
On a clean ubuntu 16.04 install I get this at the end
```
Your client config is available at ~/cosku.ovpn
If you want to add more clients, you simply need to run this script another time!
./openvpn-install.sh: line 484: syntax error near unexpected token `fi'
./openvpn-install.sh: line 484: `fi'
```

Also the script didn't ask me what cipher I want to use etc. like shown in the screenshots.

2017-02-23 21:21 UTC, Kcchouette commented
@tapir how is without `exit 0;`

2017-02-23 21:35 UTC, tapir commented
@Kcchouette same error. it only happens when I run the script first time. While adding new cert I don't get it.

2017-02-23 21:35 UTC, tapir commented
is it possible to enter domain name instead of ip?

2017-02-23 21:36 UTC, tapir commented
also on arch linux gnome network manager can't import ovpn file created with this script. it gives and error about file not being correct.

it could however import one created with nyr's script.

2017-02-23 21:44 UTC, Kcchouette requested changes

2017-02-23 21:44 UTC, Kcchouette commented on openvpn-install.sh
> +	fi
I think you forgot to remove (see the next lines)
```
# Install dependencies
pacman -Syu openvpn iptables openssl wget ca-certificates curl --needed --noconfirm
systemctl enable iptables
systemctl start iptables
fi
fi
```

2017-02-23 21:46 UTC, Kcchouette commented
@tapir what script are you using? The one on the master branch, or the one on the openvpn2.4 branch?

2017-02-23 21:46 UTC, tapir commented
openvpn 2.4 branch, that's why I'm posting here

2017-02-23 22:08 UTC, Kcchouette commented on openvpn-install.sh
> +	fi
see #40

2017-02-28 15:00 UTC, SquirrelCoder commented
I get the same exact error when running the 2.4 branch.

```
./openvpn-install.sh: line 484: syntax error near unexpected token `fi'
./openvpn-install.sh: line 484: `fi'

```

and I think after this, openvpn doesn't get properly installed and configured so one can not use the .ovpn config file.

2017-02-28 15:54 UTC, Kcchouette commented
@SquirrelCoder my PR #40 normally fixes that

2017-03-02 21:51 UTC, Angristan commented
It is indeed fixed

2017-03-03 17:31 UTC, ajthemacboy commented
Any update on iOS support? The generated ovpn file works fine on PC but won't connect on iOS:

`EVENT: RESOLVE
Contacting IP:1194 via UDP
EVENT: WAIT
SetTunnelSocket returned 1
Connecting to [IP]:1194 (IP) via UDPv4
EVENT: CONNECTION_TIMEOUT [ERR]
EVENT: DISCONNECTED`

2017-03-03 18:03 UTC, Angristan commented
If you use the 2.4 branch, it's normal, the app does not support this version (yet)

2017-03-03 21:09 UTC, ajthemacboy commented
I'm actually experiencing this on the master branch. I realize now this is the wrong place for help; I'll open an issue.

2017-03-13 12:05 UTC, pedronveloso commented
I've actually used this script to setup a Arch server with OpenVPN 2.4, if you guys are open to it I can update it. There just 2 little diferences, and everything else will be just fine :)

2017-03-16 10:49 UTC, Kcchouette approved these changes
.

2017-06-24 08:09 UTC, hybtoy commented
Still iOS Openvpn app (OpenVPN Connect) does not support elliptic curve that used in this script. Any suggestion how to use OpenVPN 2.4 with curves on iOS?
Thanks.

2017-06-24 10:28 UTC, Angristan commented
Ask the maintainer to update its app ? :/

But that got me thinking : what would require the less work would be just to use AES-GCM, ECDSA and ECDH with maxed parameters. 

But maybe I should leave to option to the type + size of certificate, type + size of *DH key and type + size of cipher ? But that would not allow older clients to connect if we use tls-crypt... So I would have to add an option to choose either tls-crypt or tls-auth ? 

Let me know what you think, then I'll probably start this PR from scratch (I'm in vacations now, sorry I started this PR 6 month ago...)

2017-06-24 12:39 UTC, hybtoy commented
> But maybe I should leave to option to the type + size of certificate, type + size of *DH key and type + size of cipher ? 

I think it would be better. 

> But that would not allow older clients to connect if we use tls-crypt... So I would have to add an option to choose either tls-crypt or tls-auth ?

Exactly!

I understand that the settings that used now are better but they are useless until we can not use them fully on all needed devices. 

So it will be better to create script that will install OVPN with settings that can be easily used on all platforms with official clients.

Thanks.

2017-08-31 21:19 UTC, migueldemoura commented
Network-Manager in Ubuntu 17.04 doesn't work with OpenVPN 2.4. Not only does the import option fail to parse the .ovpn file due to the inline certs and the invalid `block-outside-dns` parameter (only available on Windows), but after manually adding the profile it won't connect. This is probably the issue @tapir is running into.

Other than that, manually starting `openvpn profile.ovpn` works (only need to remove `block-outside-dns`).

2017-09-01 10:39 UTC, Angristan commented
That's strange, under Arch Linux I can import the .ovpn file just fine

2017-09-06 05:58 UTC, hybtoy commented
@Angristan 
1. Do we actually need support of Ubuntu 16.10? I think it will be better to support only  LTS distros or we can add 17.04.
2. Regarding client - iOS client does not support elliptic curve that used in this script, maybe we can find a compromise between security and compatibility?
3. Add Debian 9 support
4. Ability to choose encryption cipher (AES-128-GCM or AES-256-GCM)

2017-09-06 19:14 UTC, migueldemoura commented
What's holding 16.10 support anyway?

2017-09-14 10:27 UTC, closed without merging

2017-09-14 10:39 UTC, Angristan commented
See https://github.com/Angristan/OpenVPN-install/pull/96