Add connection to server through IPv6 interface
angristan/openvpn-install pull request #371
Opened 2018-12-19 20:45 UTC by tuckyapps

Adds option to establish connection with openvpn server through IPv6. This way, if your ISP is already giving you an IPv6 address, you will still be able to connect to your server.
The IPv6 address is added on client's configuration file, below the IPv4 remote instruction. This way, a user will always try to connect to the IPv4 one, and only if it has no luck, it will then try to connect using IPv6.

Note: When using udp, client will need to wait until keepalive time elapses before it tries to connect through IPv6. If you would like this switch to be fast, I suggest you use TCP protocol instead.

2019-01-30 08:28 UTC, robertkraig requested changes

2019-01-30 08:28 UTC, robertkraig commented on README.md
> +Many thanks to the [contributors](https://github.com/tuckyapps/OpenVPN-install/graphs/contributors) and Nyr's original work.
You should remove all references to `tuckyapps` if you're requesting a P.R. like this. You contribute to the Project, you don't change it to go to your repo.

2019-04-14 04:21 UTC, LiveChief commented on README.md
> +Many thanks to the [contributors](https://github.com/tuckyapps/OpenVPN-install/graphs/contributors) and Nyr's original work.
Agreed.

2019-09-07 16:50 UTC, ThePigPeppa commented
this is a bad idea.

2019-09-07 17:37 UTC, tuckyapps commented
Hi!

What do you mean?

What should I do?

Thanks in advance,

Best,

Santiago Rosenblatt 

> On Sep 7, 2019, at 6:50 PM, Peppa Pig <notifications@github.com> wrote:
> 
> this is a bad idea.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-08 06:17 UTC, angristan commented
Hello,

Can you rebase your PR against master?

2019-09-08 09:52 UTC, tuckyapps commented
How about now?

I'm sorry, did not know my commits were still influencing the pull request.

Back in January, I was asked by my company to update the comments so they
point to my repo in case others would like to download it, increasing
security and more control over the code.

Is it okay now?

Thanks again!

El dom., 8 de sep. de 2019 a la(s) 08:17, Stanislas (
notifications@github.com) escribió:

> Hello,
>
> Can you rebase your PR against master?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angristan/openvpn-install/pull/371?email_source=notifications&email_token=AG3JVRGYBJA5D3DXEQ65F2LQISKIDA5CNFSM4GLL7LCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6FIYQA#issuecomment-529173568>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AG3JVRFG4WDXJ7FX45LDW2TQISKIDANCNFSM4GLL7LCA>
> .
>

2019-09-10 01:56 UTC, angristan commented
Hello,

the diff is really messy right now, I would advise starting again from master, checking out a new branch, then adding the modifications regarding this PR then force-pushing the branch, please 🙏

2020-04-27 13:35 UTC, closed without merging