Detect firewalld and use firewall-cmd (fix for #356)
angristan/openvpn-install pull request #417
Opened 2019-04-29 02:38 UTC by BornToBeRoot

If firewalld is used (eg on CentOS 7), the firewall configuration is not correct (nat, internet access)... #356 

When firewalld is running on the system, the following rules will be applied:

```
if [[ "$PORT" == '1194' ]]; then
    firewall-cmd --zone=public --remove-service=openvpn
    firewall-cmd --permanent --zone=public --remove-service=openvpn
else
    firewall-cmd --zone=public --remove-port=$PORT/$PROTOCOL
    firewall-cmd --permanent --zone=public --remove-port=$PORT/$PROTOCOL
fi          

firewall-cmd --zone=trusted --remove-source=10.8.0.0/24
firewall-cmd --permanent --zone=trusted --remove-source=10.8.0.0/24

firewall-cmd --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
firewall-cmd --permanent --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
```

In the removed function, they are deleted:

```
# Allow incoming traffic
if [[ "$PORT" == '1194' ]]; then
    firewall-cmd --zone=public --add-service=openvpn
    firewall-cmd --permanent --zone=public --add-service=openvpn
else
    firewall-cmd --zone=public --add-port=$PORT/$PROTOCOL
    firewall-cmd --permanent --zone=public --add-port=$PORT/$PROTOCOL
fi      

 # Add trusted zone
firewall-cmd --zone=trusted --add-source=10.8.0.0/24		
firewall-cmd --permanent --zone=trusted --add-source=10.8.0.0/24

# Set NAT for the VPN subnet
firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
```

I copied these rules from Nyr/openvpn-install.

The rules with firewall-cmd are applied permanent and not with the systemd script/service... I see some problems if you do this with the script:
1) If you don't use the parameter `--permanent` in the script, the rules are only temporary. When you restard the firewalld service or use `firewall-cmd --reload`, the configuration is lost until you restart `iptables-openvpn`
2) If you use `--permanent` in the script and openvpn is uninstalled with this script, the rules are still active until you restart firewalld or reload the configration.

Maybe you can add both, the temporary and the permanent rule in the service. For my needs (an always running vpn), i don't see the added value of this systemd service.

I tested the script only on my CentOS 7.

2020-03-03 01:21 UTC, randshell requested changes
I suggest defining a new openvpn service instead of adding port and protocols without a name or description.

Changes are not tested.

2020-03-03 01:21 UTC, randomshell commented on openvpn-install.sh
> +		fi
```suggestion
            # Define new openvpn service
            cp /usr/lib/firewalld/services/openvpn.xml /etc/firewalld/services
            sed -i "s|udp|${PROTOCOL}|" /etc/firewalld/services/openvpn.xml
            sed -i "s|1194|${PORT}|" /etc/firewalld/services/openvpn.xml
                    
            firewall-cmd --zone=public --add-service=openvpn
            firewall-cmd --permanent --zone=public --add-service=openvpn
```

2020-03-03 01:21 UTC, randomshell commented on openvpn-install.sh
> +		    fi
```suggestion
            firewall-cmd --zone=public --remove-service=openvpn
            firewall-cmd --permanent --zone=public --remove-service=openvpn
            
            # Remove defined openvpn service
            rm /etc/firewalld/services/openvpn.xml
```

2020-04-30 22:20 UTC, angristan requested changes

2020-04-30 22:20 UTC, angristan commented on openvpn-install.sh
> +            firewall-cmd --permanent --zone=public --add-port="$PORT/$PROTOCOL"
Just keep the else.

```suggestion
            firewall-cmd --zone=public --add-port="$PORT/$PROTOCOL"
            firewall-cmd --permanent --zone=public --add-port="$PORT/$PROTOCOL"
```

2020-04-30 22:20 UTC, angristan commented on openvpn-install.sh
> +                firewall-cmd --permanent --zone=public --remove-port="$PORT/$PROTOCOL"
Same here
```suggestion
                firewall-cmd --zone=public --remove-port="$PORT/$PROTOCOL"
                firewall-cmd --permanent --zone=public --remove-port="$PORT/$PROTOCOL"
```

2020-04-30 22:21 UTC, angristan commented
Thank you for this!

2020-05-01 05:33 UTC, randomshell commented
@angristan what about my suggestion of defining a new service to keep things clean? You resolved it without an explanation.

Thanks

2020-05-06 11:16 UTC, randomshell commented
@angristan firewalld was supported but you removed it in #291. Why?

2020-05-10 12:31 UTC, angristan commented
@randomshell sorry, that seems like a cleaner solution indeed

https://github.com/angristan/openvpn-install/pull/291 was about handling all the firewall rules with systemd and iptables. I dropped firewalld for the sake of simplicity, and as written in a comment I'm pretty sure I tested these modifications on all distributions, even after reboots. Not sure what changed since then.

2020-05-18 21:49 UTC, randomshell commented
As a note, with SNAT if the IP changes then users can't connect anymore. Should we use MASQUERADE in firewalld like we do with iptables or update the iptables commands instead?

Source https://unix.stackexchange.com/questions/21967/difference-between-snat-and-masquerade

2020-06-28 19:45 UTC, randomshell commented
@BornToBeRoot could you please review my initial suggestions of the new service and update your PR?

This issue is stale for a year and blocks our support for CentOS

2020-06-28 20:56 UTC, BornToBeRoot commented
@randomshell i updated the PR.

@angristan there are some conflicts that needs to be resolved. Maybe you can take a look at it and then merge the PR.

2020-06-28 21:37 UTC, randomshell commented
@BornToBeRoot Great!

The only thing missing is a `firewall-cmd --reload` after adding or removing the rules. I know you accepted the suggested changes but I realized that we need a reload after.

2022-01-18 06:58 UTC, jcastilloalonso commented
This might bring issues if the setup is done behind a NAT. Ideally we would use Masquerating instead of SNAT to avoid this issue and not mess with all the headache.

2025-03-16 22:31 UTC, closed without merging