Add Gentoo and OpenRC Support
angristan/openvpn-install pull request #480
Opened 2019-09-09 23:09 UTC by r7l

Hello, i've added support for Gentoo Linux. Would it be possible to merge it as this script is really helpful but lacks of support for Gentoo Linux users. Since Gentoo is flexible about the init system, i've also added support for OpenRC. The overhead for the support of 2 init systems isn't too big as i've wrapped a simple function around it.

2019-09-10 01:49 UTC, angristan commented on openvpn-install.sh
> +		elif [[ "$OS" = 'arch' ]]; then
Should be `gentoo` here I guess?

2019-09-10 01:50 UTC, angristan commented
I wouldn't usually agree to that, but first of all, thank you for doing things properly! 👍

2019-09-10 09:02 UTC, r7l commented
Thanks for your response. I've fixed that issue with the uninstall. Didn't really notice as the scripts installs OpenVPN anyways each time you redo the process.

I've also added Gentoo into this description for the error and updated Readme.md. Somehow i forgot about this.

Surely it is your project but the support for Gentoo and OpenRC doesn't seem like a big change to the script for me. It's just the additional init function, few replaced strings and a couple more IFs.

2019-09-16 18:24 UTC, r7l commented
Is there any chance of this ever being merged or you decided against it?

2019-09-18 01:39 UTC, angristan commented
Sorry, I'm abroad so I have less time for GitHub stuff as you can see on my graph 🙂

I also I have to see how to setup a Gentoo VM to test this PR...

2019-09-18 01:47 UTC, angristan commented
Gentoo is not supported natively on:

- Digital Ocean
- Vultr
- GCP
- AWS
- Hetzner
- ...

That's why I was against this initially. First, that means very few people would actually use the script on Gentoo. Secondly, that means I can't easily test it on Gentoo, and that's a problem...

2019-09-18 02:04 UTC, tidux commented
AWS AMIs: http://www.dowdandassociates.com/products/pygoscelis-papua/

2019-09-18 02:36 UTC, angristan commented
Thanks @tidux

2019-09-18 05:41 UTC, angristan commented
Errors I see:

```
+ sed -i 's/^RANDFILE/#RANDFILE/g' pki/openssl-easyrsa.cnf
sed: can't read pki/openssl-easyrsa.cnf: No such file or directory
```

```
+ /etc/init.d/iptables-openvpn start
 * Caching service dependencies ...                                                                                                                                         [ ok ]
 * Starting  ...                                                                                                                                                            [ !! ]
 * ERROR: iptables-openvpn failed to start
```

2019-09-18 05:48 UTC, angristan requested changes

2019-09-18 05:48 UTC, angristan commented on openvpn-install.sh
> +    eend $?
This results in `eend 1` being written, so the init script fails

2019-09-18 05:48 UTC, angristan commented on openvpn-install.sh
> +    eend $?
Same here

2019-09-18 05:55 UTC, angristan commented
This workaround should be skipped on Gentoo since it does not seem to be affected:

```sh
# Workaround to remove unharmful error until easy-rsa 3.0.7
# https://github.com/OpenVPN/easy-rsa/issues/261
sed -i 's/^RANDFILE/#RANDFILE/g' pki/openssl-easyrsa.cnf
```

2020-04-27 13:33 UTC, closed without merging