Custom IP-subnet
angristan/openvpn-install pull request #551
Opened 2020-02-29 12:12 UTC by timbo2k

Hello

first of all thanks for your amazing script setting up openvpn-server - used that several times until now.
I added a minor feature for customizing the IP-subnet of openvpn-server and its clients including the regarding questions.
Successfully tested on CentOS7.

I'm open for discussion. If those changes are not wanted please just reject PR.

thanks timbo

2020-02-29 12:17 UTC, timbo2k commented
just noticed that there is a similar PR (https://github.com/angristan/openvpn-install/pull/550) just a few hours ago with the same topic, did saw that before - Sorry

2020-03-29 20:33 UTC, HenryNe requested changes
I suggest to check the changes with https://www.shellcheck.net/ online.

2020-03-29 20:33 UTC, HenryNe commented on openvpn-install.sh
> +access-control: $VPN_SUBNET.1/24 allow
Expressions don't expand in single quotes, use double quotes for that.

2020-03-29 20:39 UTC, HenryNe commented on openvpn-install.sh
> +			echo 'interface: $VPN_SUBNET.1
Expressions don't expand in single quotes, use double quotes for that.

```suggestion
			echo "interface: $VPN_SUBNET.1
```

2020-03-29 20:40 UTC, HenryNe approved these changes

2020-03-29 20:41 UTC, HenryNe requested changes
Expressions don't expand in single quotes, and a variable in left side.
I suggest to check the changes with https://www.shellcheck.net/ online.
_Sorry for double post. I'm fighting with github._

2020-04-30 22:13 UTC, angristan commented
Hi @timbo2k, thanks for you contribution. There is indeed a PR at #550, so we'll good with that one.

Cheers!

2020-04-30 22:13 UTC, closed without merging