Comments about DNS
angristan/openvpn-install pull request #598
Opened 2020-03-30 22:56 UTC by HenryNe

2020-03-30 23:26 UTC, randshell approved these changes

2020-04-01 09:32 UTC, angristan requested changes

2020-04-01 09:32 UTC, angristan commented on openvpn-install.sh
> +		2) # Self-hosted DNS Resolver (Unbound)
```suggestion
		2) # Self-hosted DNS resolver (Unbound)
```

2020-04-02 14:30 UTC, merged

2020-04-02 14:31 UTC, angristan commented
Thanks 🙂