Add DNS IPv6 for self-hosted DNS Resolver
angristan/openvpn-install pull request #600
Opened 2020-03-30 23:00 UTC by HenryNe

2020-03-30 23:33 UTC, randshell requested changes
Unbound is configured to listen only on IPv4 
https://github.com/angristan/openvpn-install/blob/44105eb06068ef95ff3217924ee615e8757f7516/openvpn-install.sh#L107
https://github.com/angristan/openvpn-install/blob/44105eb06068ef95ff3217924ee615e8757f7516/openvpn-install.sh#L118

2020-03-30 23:51 UTC, randomshell commented
You need to append `interface: fd42:42:42:42::1`, `access-control: fd42:42:42:42::/112 allow` and `private-address:  fd42:42:42:42::/112` to unbound config.

2020-03-31 15:21 UTC, HenryNe commented
@randomshell thanks for the watch. unbound.conf changed, .
Debian 9 as server tested successfully.

On the client side have tested with an explizit IPv6 command:

```
$ host -v -6 www.google.com
...
;; ANSWER SECTION:
www.google.com.         229     IN      AAAA    2a00:1450:4001:81d::2004
...
Received 82 bytes from fd42:42:42:42::1#53 in 91 ms
```

2020-03-31 15:30 UTC, randomshell commented on openvpn-install.sh
> +access-control: fd42:42:42:42::/112 allow' >> /etc/unbound/unbound.conf
Fix unbound configuration when already installed
```suggestion
access-control: fd42:42:42:42::/112 allow' >> /etc/unbound/openvpn.conf
```

2020-03-31 15:31 UTC, randshell requested changes

2020-03-31 15:31 UTC, randomshell commented on openvpn-install.sh
> +access-control: fd42:42:42:42::/112 allow' >> /etc/unbound/unbound.conf
Fix unbound configuration when already installed
```suggestion
access-control: fd42:42:42:42::/112 allow' >> /etc/unbound/openvpn.conf
```

2020-03-31 20:44 UTC, randshell approved these changes
Thanks!

2020-04-01 09:20 UTC, angristan commented
Thanks! While I'm not against this per se, what is the point of a dual-stack **local** resolver?

2020-04-01 20:37 UTC, HenryNe commented
> 
> 
> Thanks! While I'm not against this per se, what is the point of a dual-stack **local** resolver?

My server is a IPv6 only system. So, in my case VPN is usable only via IPv6. This server has no IPv4 default route. This server give not a real dual stack VPN. Only the IPv6 part is usable. That's why I fall in some pitfalls, where IPv6 is not full usable. - I would witsh to disable IPv4. But this would be an other feature.

In an other case, Vagrant have no IPv6 support. With VPN connection to the IPv6 server I have full IPv6 connections in Vagrant, and can test IPv6 only systms in Vagrant.

2020-04-02 14:32 UTC, angristan commented
OK. So with this PR Unbound will be usable on:

- IPv4-only systems
- Dual-stack
- IPv6-only systems

Correct? If that's the case, then I'm all for it 👍

2020-04-02 18:35 UTC, HenryNe commented
Yes, and explicit **yes** for IPv6-only.

2020-04-30 21:23 UTC, angristan requested changes
OK with this, just need a rebase against master 👍

2020-04-30 22:03 UTC, angristan approved these changes

2020-04-30 22:04 UTC, merged