Add support for `client-configuration-dir`
angristan/openvpn-install pull request #609
Opened 2020-04-03 02:13 UTC by randomshell

I didn't add the code to create `/etc/openvpn/ccd/$CLIENT` files because it's cleaner to have there only the clients that are using the client specific options.

Fix #606

2020-04-04 10:25 UTC, HenryNe requested changes

2020-04-04 10:25 UTC, HenryNe commented on openvpn-install.sh
> +	mkdir /etc/openvpn/ccd
Supress error message for existing directory
```suggestion
	mkdir -p /etc/openvpn/ccd
```

2020-04-04 19:56 UTC, HenryNe approved these changes

2020-04-06 12:37 UTC, angristan requested changes

2020-04-06 12:37 UTC, angristan commented on openvpn-install.sh
> +	# Create ccd dir
```suggestion
	# Create client-config-dir dir
```

2020-04-10 15:44 UTC, angristan approved these changes

2020-04-10 15:49 UTC, merged