Update distro compatibility list
angristan/openvpn-install pull request #654
Opened 2020-05-02 03:31 UTC by randomshell

- Centos 7 i386 is supported. armhf images and epel repository are available [link](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp#How_Can_I_Enable_EPEL_7_on_armhfp_.3F)
- Centos 8 isn't available on armhf but has images for arm64. Epel for armhf can be used on arm64 [link](http://isoredirect.centos.org/altarch/)
- Debian 8 for armhf and arm64 is available [link](https://packages.debian.org/jessie/openvpn)
- Debian 9 for i386 is available
- There are some images for Ubuntu 16.04 armhf and arm64 but compatibility is ? [link](http://old-releases.ubuntu.com/releases/xenial/)
- Ubuntu 18.04 supports i386, armhf and arm64 because of Ubuntu Mate [link](https://ubuntu-mate.org/download/)

2020-05-10 12:14 UTC, angristan commented
> Debian 8 for armhf and arm64 is available

No, we use the [official APT repo](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos) because we need 2.4 :)

2020-05-11 15:58 UTC, randomshell commented
So it doesn't fallback to the debian repository if it hasn't the needed architecture?

Anyway Debian 8 is end of life on 30 June.

2020-06-28 19:58 UTC, randomshell commented
I removed support for Debian 8 now.

2020-07-27 13:20 UTC, angristan commented
These lines need to be removed too:

https://github.com/angristan/openvpn-install/blob/7dbc4d81279b9c8a6dee4726b73e1dcba67d26f7/openvpn-install.sh#L656-L660

2020-07-27 13:22 UTC, angristan requested changes

2020-07-27 13:22 UTC, angristan commented on README.md
> +| Ubuntu 16.04    | ✅   | ✅    | ❔    | ❔    |
For ARM it will fall back to Ubuntu packages which are too old, so we have to keep `❌`

2020-07-28 10:23 UTC, angristan approved these changes
Ok! LGTM

2020-07-28 10:24 UTC, merged