Rebased: Making Client Revocation Headless and Documenting New Feature
angristan/openvpn-install pull request #725
Opened 2020-09-05 21:18 UTC by Namielusi

Hello, this PR adds headless client revocation. The code was taken from #489 (close both when this PR gets merged). Closes #486.

I've taken dumrauf's work and made a rebase, so the PR is relevant once again and ready to be merged.

I don't know bash that much, just thought a little help won't hurt. Tell me if there's anything else I can do regarding this feature.

2020-09-06 08:41 UTC, randomshell requested changes
I didn't quite get why there are 2 PRs. Anyway comment for both @Namielusi here and @dumrauf in #489:
- the regex of the client needs to be updated with a dash to follow the `newClient` function https://github.com/angristan/openvpn-install/blob/423419de74ad945b905c46d097defaf490f60636/openvpn-install.sh#L1050
- it would be nice to check that the headlessly provided `$CLIENT` exists before running easyrsa to revoke it. easyrsa checks it anyway but it's better that we handle this case too

2020-09-06 08:47 UTC, Namielusi commented
Hello, @randomshell. I've created a second PR as the initial one seems to be abandoned. I want to help with merging this little PR, but I can't do it in #489 as I don't have write access, so I created a new PR.

Basically, I think #489 can be closed in favor of this PR.

About other things you've mentioned, thank you, I'll see what I can do about it.

2022-04-21 08:30 UTC, thachphongphong commented
where you set CLIENTNUMBER ?

2025-06-22 08:10 UTC, W01v3n commented
Hey guys, been a while, any news on that one? It'd be nice if that option could be headless.

2025-12-13 18:52 UTC, angristan commented
Supported with https://github.com/angristan/openvpn-install/pull/1328 and https://github.com/angristan/openvpn-install/pull/1387

2025-12-13 18:52 UTC, closed without merging